# Generated by Django 6.0.3 on 2026-03-24 08:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название редкости')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет в HEX')),
                ('multiplier', models.FloatField(default=1.0, verbose_name='Множитель шанса выпадения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Редкость',
                'verbose_name_plural': 'Редкости',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Users_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikname', models.CharField(max_length=100, unique=True, verbose_name='Никнейм')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('email', models.CharField(max_length=200, verbose_name='Почта пользователя')),
                ('total_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Всего очков')),
                ('current_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Текущие очки')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название карточки')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers_card/', verbose_name='Обложка карточки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('strenth', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Сила карты')),
                ('health', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Жизни карты')),
                ('defence', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Защита карты')),
                ('attribute', models.CharField(blank=True, max_length=100, null=True, verbose_name='Атрибут карточки')),
                ('price_points', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Цена в очках')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('rarity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='module_project.rarity', verbose_name='Редкость')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='module_project.users_system', verbose_name='Автор карточки')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='В избранном')),
                ('is_equipped', models.BooleanField(default=False, verbose_name='Экипирована')),
                ('times_won', models.IntegerField(default=0, verbose_name='Количество побед')),
                ('obtained_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='module_project.cards', verbose_name='Карточка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='module_project.users_system', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Карточка в инвентаре',
                'verbose_name_plural': 'Карточки в инвентаре',
                'ordering': ['-obtained_at'],
                'unique_together': {('user', 'card')},
            },
        ),
        migrations.CreateModel(
            name='Gacha_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Потрачено очков')),
                ('obtained_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gacha_history', to='module_project.cards', verbose_name='Полученная карточка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gacha_history', to='module_project.users_system', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История гачи',
                'verbose_name_plural': 'История гачи',
                'ordering': ['-obtained_at'],
            },
        ),
        migrations.CreateModel(
            name='Battle_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_victory', models.BooleanField(verbose_name='Победа')),
                ('points_earned', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Заработано очков')),
                ('user_power', models.IntegerField(default=0, verbose_name='Сила пользователя')),
                ('robot_power', models.IntegerField(default=0, verbose_name='Сила робота')),
                ('battle_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата боя')),
                ('robot_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_as_robot', to='module_project.cards', verbose_name='Карточка робота')),
                ('user_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_as_user', to='module_project.user_inventory', verbose_name='Карточка пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='module_project.users_system', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История боя',
                'verbose_name_plural': 'История боев',
                'ordering': ['-battle_date'],
            },
        ),
    ]
