# Generated by Django 6.0.3 on 2026-04-02 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название атрибута')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='attributes_icons/', verbose_name='Иконка атрибута')),
                ('color', models.CharField(default='#FFFFFF', help_text='Например: #FF0000 для красного', max_length=7, verbose_name='Цвет атрибута в HEX')),
                ('strength_bonus', models.FloatField(default=1.0, help_text='Множитель силы для карт этого атрибута', verbose_name='Бонус к силе')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='cards',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='module_project.attribute', verbose_name='Атрибут карточки'),
        ),
    ]
